# This is a basic script that extracts and loads the bike point api data via main.py script
#run every hour or when button pressed

name: Bike Point Ingestion

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:

  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build: 
    runs-on: ubuntu-latest 
    environment: Bike Point Environment
    steps: 
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Setup python environment
        uses: actions/setup-python@v4
        with: 
          python-version: '3.11'

      - name: install packages
        run: pip install -r requirements.txt

      - name: run main python script
        env: 
          aws_acces: ${{secrets.ACCESS_KEY}}
          aws_secret: ${{secrets.SECRET_KEY}}
        run: python main.py
        
      
